### ISSUE TITLE
can't open file 'Scripture.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Saibot942** [engineervix/Bible-Playlist-Generator#3]
Hi again, Victor.

Now that the Python script is executing successfully, I tested the _make_one_week_playlist.sh_ script in Cygwin.  There is a typo on line 41 of the current version where it's attempting to call 'Scripture.py' instead of 'scripture_playlist_gen.py'.   This results in the error:

> C:\asdf\Installed\python27\python.exe: can't open file 'Scripture.py': [Errno 2] No such file or directory

After correcting that call, the shell script now runs properly.  Adding the date to the playlist name and directory name is a nice feature, btw.

**Comment by engineervix** [comment]
Thank you so much @Saibot942 for pointing this out! I had renamed the python script on my computers to `Scripture.py`! I have [revised `make_one_week_playlist.sh`](https://github.com/engineervix/Bible-Playlist-Generator/commit/e5bbad4d29d98935665d09897bc030b6ef659426) so that it calls `scripture_playlist_gen.py` instead of `Scripture.py`. Grace and Peace
